### PR TITLE
Deserializer is not maintaining `previewFeatures` and `binaryTargets` options

### LINKED ISSUE #174: `previewFeatures` and `binaryTargets` options are being removed from schema
When running this transformer, the `previewFeatures` and `binaryTargets` options are being removed from the client generator.

### PR DESCRIPTION
**Pull request by aniravi24**
The deserializers aren't accounting for the `previewFeatures` and `binaryTargets` options being set, so it never adds them back into the schema if they are present.

Also, whenever syncing with the DB, Prisma puts the generators above the datasource, so made a small change to re-order the output to match what Prisma is doing.

fixes #174

### CODE REVIEW

**Comment by aniravi24** [comment]
@botika sorry to bump you! Wanted to check if you could merge this and do a release.

**Comment by zzau13** [comment]
Sorry, I have been very busy and have not been able to bring the github. I have updated the whole repo. Could you update your commits so I can merge?

**Comment by aniravi24** [comment]
@zzau13 I updated the PR, but you may need to regenerate the snapshot for the deserializer test.

**Comment by zzau13** [comment]
can you update with `pnpm test -- -u` thank

**Comment by aniravi24** [comment]
@zzau13 done!

**Review by zzau13 — APPROVED** [review]

**Pull request merged**
